sudo: required
os:
  - linux
  - osx

osx_image: xcode7.1

services:
  - docker
  - postgresql

install:
  - make dependencies

script:
  - make test

env:
  - PGHOST=localhost PGUSER=travis PGPORT=5432 DBNAME=spec
